<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '男款展厅',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => 134,
    'level' => 0,
    'id' => '1',
    'name' => '男款展厅',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '品牌',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '52',
    'name' => '品牌',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '商务测试款',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '139',
    'name' => '商务测试款',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '边框',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '边框',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '半框',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 47,
    'level' => 2,
    'id' => '27',
    'name' => '半框',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '无框',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '28',
    'name' => '无框',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '全框',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 81,
    'level' => 2,
    'id' => '26',
    'name' => '全框',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '大小',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '大小',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '中框',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '38',
    'name' => '中框',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '大框',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '39',
    'name' => '大框',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '小框',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '40',
    'name' => '小框',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '颜色',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '6',
    'name' => '颜色',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '咖啡色',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '30',
    'name' => '咖啡色',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '黑白色系',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '49',
    'name' => '黑白色系',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '蓝色',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '31',
    'name' => '蓝色',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '彩色系',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '50',
    'name' => '彩色系',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '银色',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '47',
    'name' => '银色',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '花纹系',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '51',
    'name' => '花纹系',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '黑色',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '29',
    'name' => '黑色',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '玳瑁色',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '48',
    'name' => '玳瑁色',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '材质',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '10',
    'name' => '材质',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '塑钢',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '37',
    'name' => '塑钢',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => 'TR',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '24',
    'name' => 'TR',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '金属合金',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '41',
    'name' => '金属合金',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '弹力钢',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '8',
    'name' => '弹力钢',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '板材',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 84,
    'level' => 2,
    'id' => '42',
    'name' => '板材',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '镜片',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '140',
    'name' => '镜片',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '碳纤维',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '35',
    'name' => '碳纤维',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '聚合物',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '46',
    'name' => '聚合物',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '纯钛',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '23',
    'name' => '纯钛',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '款式',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '款式',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '极客款',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '4',
    'name' => '极客款',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '复古款',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '33',
    'name' => '复古款',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '经典款',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '34',
    'name' => '经典款',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '时尚款',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '25',
    'name' => '时尚款',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '商务款',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '32',
    'name' => '商务款',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '女款展厅',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '女款展厅',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '材质',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '材质',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '聚合物',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '65',
    'name' => '聚合物',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '塑钢',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '62',
    'name' => '塑钢',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '金属',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 40,
    'level' => 2,
    'id' => '59',
    'name' => '金属',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '碳纤维',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '63',
    'name' => '碳纤维',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => 'TR',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 15,
    'level' => 2,
    'id' => '60',
    'name' => 'TR',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '钛架',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 7,
    'level' => 2,
    'id' => '64',
    'name' => '钛架',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '弹力钢',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '61',
    'name' => '弹力钢',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '板材',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 104,
    'level' => 2,
    'id' => '58',
    'name' => '板材',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '边框',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => '边框',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '无框',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '68',
    'name' => '无框',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '全框',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '66',
    'name' => '全框',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '半框',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '67',
    'name' => '半框',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '大小',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '大小',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '大框',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '71',
    'name' => '大框',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '小框',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '69',
    'name' => '小框',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '中框',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '70',
    'name' => '中框',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '颜色',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => 0,
    'level' => 1,
    'id' => '12',
    'name' => '颜色',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '黑白色系',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '78',
    'name' => '黑白色系',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '紫色',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '75',
    'name' => '紫色',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '黑色',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '72',
    'name' => '黑色',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '彩色系',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '79',
    'name' => '彩色系',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => '红色',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '76',
    'name' => '红色',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => '咖啡色',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '73',
    'name' => '咖啡色',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '花纹系',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '80',
    'name' => '花纹系',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '玳瑁色',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '77',
    'name' => '玳瑁色',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => '蓝色',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => '蓝色',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '品牌',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '品牌',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '款式',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '款式',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '商务款',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '55',
    'name' => '商务款',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '时尚款',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '56',
    'name' => '时尚款',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '复古款',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '53',
    'name' => '复古款',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '极客款',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '57',
    'name' => '极客款',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '经典款',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '54',
    'name' => '经典款',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '镜片展厅',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '45',
    'name' => '镜片展厅',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '材质',
    'measure_unit' => '10',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '100',
    'name' => '材质',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => 'MR-8',
    'measure_unit' => '10',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => 'MR-8',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '玻璃',
    'measure_unit' => '10',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '104',
    'name' => '玻璃',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '树脂',
    'measure_unit' => '10',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '101',
    'name' => '树脂',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => 'PC',
    'measure_unit' => '10',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => 'PC',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '品牌',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '123',
    'name' => '品牌',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => 'LOHO',
    'measure_unit' => '',
    'parent_id' => '123',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '124',
    'name' => 'LOHO',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '度数',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '117',
    'name' => '度数',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '0-600度',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '119',
    'name' => '0-600度',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '200-400度',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '120',
    'name' => '200-400度',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '400-600度',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '121',
    'name' => '400-600度',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '0-200度',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '118',
    'name' => '0-200度',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '600度以上',
    'measure_unit' => '',
    'parent_id' => '117',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '122',
    'name' => '600度以上',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '类型',
    'measure_unit' => '10',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '92',
    'name' => '类型',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '偏光片',
    'measure_unit' => '7',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '97',
    'name' => '偏光片',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '染色镜片',
    'measure_unit' => '5',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '94',
    'name' => '染色镜片',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '渐进多焦点镜片',
    'measure_unit' => '6',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '98',
    'name' => '渐进多焦点镜片',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '抗疲劳片',
    'measure_unit' => '4',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '95',
    'name' => '抗疲劳片',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '变色镜片',
    'measure_unit' => '10',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '99',
    'name' => '变色镜片',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '防辐射镜片',
    'measure_unit' => '5',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '96',
    'name' => '防辐射镜片',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '单光片',
    'measure_unit' => '6',
    'parent_id' => '92',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '93',
    'name' => '单光片',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '加膜',
    'measure_unit' => '10',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '11',
    'goods_num' => 0,
    'level' => 1,
    'id' => '105',
    'name' => '加膜',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '超级膜',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '116',
    'name' => '超级膜',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '翡翠膜',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '113',
    'name' => '翡翠膜',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '钻晶A2',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '110',
    'name' => '钻晶A2',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '莲花膜',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '莲花膜',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '钻晶A+',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '114',
    'name' => '钻晶A+',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '超级防雾',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '111',
    'name' => '超级防雾',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '钻石硬',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '108',
    'name' => '钻石硬',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '滤光膜',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '115',
    'name' => '滤光膜',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '铂金膜',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '112',
    'name' => '铂金膜',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '莱宝膜',
    'measure_unit' => '',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '109',
    'name' => '莱宝膜',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '加硬',
    'measure_unit' => '10',
    'parent_id' => '105',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '106',
    'name' => '加硬',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '折射率',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '125',
    'name' => '折射率',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '1.67',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '129',
    'name' => '1.67',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '1.50',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '126',
    'name' => '1.50',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '1.70',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '130',
    'name' => '1.70',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '1.56',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '127',
    'name' => '1.56',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '1.61',
    'measure_unit' => '',
    'parent_id' => '125',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '128',
    'name' => '1.61',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '太阳镜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '7',
    'goods_num' => 11,
    'level' => 0,
    'id' => '3',
    'name' => '太阳镜',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '款式',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '款式',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '经典款',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '81',
    'name' => '经典款',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '时尚款',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '82',
    'name' => '时尚款',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '材质',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '17',
    'name' => '材质',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '金属',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '84',
    'name' => '金属',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => 'TR',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '85',
    'name' => 'TR',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '钛架',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '86',
    'name' => '钛架',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '板材',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '83',
    'name' => '板材',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '大小',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '21',
    'name' => '大小',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '小框',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '87',
    'name' => '小框',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '大框',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '88',
    'name' => '大框',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '框型',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '18',
    'name' => '框型',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '方型',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '91',
    'name' => '方型',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '椭圆型',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '89',
    'name' => '椭圆型',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '圆型',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '90',
    'name' => '圆型',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '价格',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '22',
    'name' => '价格',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '品牌',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => '品牌',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => 'tr',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '141',
    'name' => 'tr',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '眼镜参数',
    'measure_unit' => '毫米',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '137',
    'name' => '眼镜参数',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '镜框展厅',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '6',
    'level' => 0,
    'id' => '134',
    'name' => '镜框展厅',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '男款镜框',
    'measure_unit' => '',
    'parent_id' => '134',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '135',
    'name' => '男款镜框',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '女款镜框',
    'measure_unit' => '',
    'parent_id' => '134',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '136',
    'name' => '女款镜框',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => '镜腿展厅',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '131',
    'name' => '镜腿展厅',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '男款镜腿',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '132',
    'name' => '男款镜腿',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '女款镜腿',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '133',
    'name' => '女款镜腿',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '眼镜',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '138',
    'name' => '眼镜',
  ),
);
?>